
test:
	./run_DT.sh # Trinity w/ just chimeric reads
	./run_DTI.sh # Trinity including unmapped and chimeric reads

	./run_DO.sh # Oases w/ just chimeric reads
	./run_DOI.sh # Oases w/ chimeric + unmapped reads

	./run_DOMI.sh # Oases multi-kmer w/ chimeric and unmapped reads


